### ISSUE TITLE
Bloodborne

### ISSUE THREAD

**Issue by RockeyLol** [was421/PaintedWorldsInfo#1]
Hi. I have a question. Could you implement multiplayer in Bloodborne? It seems to be similar to DS3. The emulator is progressing. It would blow up the community.

**Comment by RockeyLol** [comment]
And another question as a professional. I am also an experienced modder but in a different field. I saw co-op mods for Resident Evil 4 and Devil May Cry where they simply added a network component to the game through trainers. Can't you do this with many games? Let's say you spawn NPCs and deadly players and let them run and synchronize their movements. Like the Skyrim mod he made, for example.

**Comment by was421** [comment]
Seems like you have a good grasp of the concepts, shouldn't be anything too complex, maybe a weekend's worth of work. Looking forward to seeing what you can do.

**Comment by RockeyLol** [comment]
I see you are not interested. Then the question is, how much would your interest cost?
